version: '3.4'

services:
  db:
    environment:
      - POSTGRES_PASSWORD=passw0rd!
    volumes:
      - pgdata:/var/lib/postgresql/data

  urlshortner:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CUSTOMCONNSTR_URLSHORTNER=Host=db;Database=url_shortner;Username=postgres;Password=passw0rd!
    ports:
      - 8080:80

volumes:
  pgdata: